import type { LayerDefinition } from "./types";
import { fetchCommercialFlights, fetchMilitaryFlights } from "./lib/sources/flights";
import {
  fetchGnss,
  fetchMilitarySats,
  fetchSpaceStations,
  fetchStarlink,
} from "./lib/sources/satellites";
import {
  fetchConflictZones,
  fetchCyberThreats,
  fetchDiseaseOutbreaks,
  fetchInternetOutages,
  fetchProtests,
  fetchWarMonitor,
} from "./lib/sources/gdelt";
import { fetchEarthquakes, fetchGpsJamming } from "./lib/sources/misc";
import { fetchPsyopsIndex } from "./lib/sources/psyops";
import { fetchTankers, fetchVessels } from "./lib/sources/ais";
import {
  fetchChokepoints,
  fetchDatacenters,
  fetchManufacturing,
  fetchMilitaryBases,
  fetchNuclearSites,
  fetchNuclearWarheads,
  fetchPipelines,
  fetchSanctions,
  fetchSpaceports,
  fetchStorageFacilities,
  fetchTariffs,
  fetchTradeRoutes,
  fetchUnderseaCables,
} from "./lib/sources/reference";

const MIN = 60_000;

export const LAYERS: LayerDefinition[] = [
  // ── Conflict & Security ────────────────────────────────────────────────────
  {
    id: "conflict-zones",
    label: "Conflict zones",
    category: "Conflict & Security",
    kind: "live",
    description: "Geolocated armed-clash, airstrike and militant activity from global news.",
    source: "GDELT 2.0 GEO API",
    sourceUrl: "https://www.gdeltproject.org/",
    style: { type: "circle", color: "#ff4d4d", radius: 5 },
    refreshMs: 10 * MIN,
    fetch: fetchConflictZones,
  },
  {
    id: "war-monitor",
    label: "Current war-zone monitor",
    category: "Conflict & Security",
    kind: "live",
    description: "Last-24h frontline strikes, bombardment and casualty reporting.",
    source: "GDELT 2.0 GEO API",
    sourceUrl: "https://www.gdeltproject.org/",
    style: { type: "circle", color: "#ff8000", radius: 6 },
    refreshMs: 8 * MIN,
    fetch: fetchWarMonitor,
  },
  {
    id: "protests",
    label: "Protests & civil unrest",
    category: "Conflict & Security",
    kind: "live",
    description: "Protests, demonstrations, riots and strikes from global news.",
    source: "GDELT 2.0 GEO API",
    sourceUrl: "https://www.gdeltproject.org/",
    style: { type: "circle", color: "#ffd11a", radius: 5 },
    refreshMs: 12 * MIN,
    fetch: fetchProtests,
  },
  {
    id: "military-bases",
    label: "Military bases",
    category: "Conflict & Security",
    kind: "reference",
    description: "Major strategic military installations worldwide.",
    source: "Curated (public records)",
    style: { type: "circle", color: "#7fb3ff", radius: 5 },
    refreshMs: 0,
    fetch: fetchMilitaryBases,
  },
  {
    id: "nuclear-sites",
    label: "Nuclear sites",
    category: "Conflict & Security",
    kind: "reference",
    description: "Weapons, enrichment, research and strategic power facilities.",
    source: "Curated (IAEA/FAS/public records)",
    style: { type: "circle", color: "#39ff14", radius: 5 },
    refreshMs: 0,
    fetch: fetchNuclearSites,
  },
  {
    id: "nuclear-warheads",
    label: "Nuclear warheads (by state)",
    category: "Conflict & Security",
    kind: "reference",
    description: "Estimated warhead inventories of the nine nuclear-armed states.",
    source: "FAS / SIPRI estimates",
    sourceUrl: "https://fas.org/initiative/status-world-nuclear-forces/",
    style: { type: "circle", color: "#ff1a1a", radius: 8 },
    refreshMs: 0,
    fetch: fetchNuclearWarheads,
  },
  {
    id: "sanctions",
    label: "Sanctions imposed",
    category: "Conflict & Security",
    kind: "reference",
    description: "Countries under major US/UN/EU sanctions programmes.",
    source: "Curated (OFAC/UN/EU)",
    style: { type: "circle", color: "#c071ff", radius: 7 },
    refreshMs: 0,
    fetch: fetchSanctions,
  },

  // ── Maritime ───────────────────────────────────────────────────────────────
  {
    id: "vessels",
    label: "Maritime vessels / ship traffic",
    category: "Maritime",
    kind: "live",
    description: "Live AIS positions of ships in view (all vessel types).",
    source: "aisstream.io (AIS)",
    sourceUrl: "https://aisstream.io/",
    style: { type: "circle", color: "#00e0ff", radius: 3 },
    refreshMs: 15_000,
    requiresKey: "VITE_AISSTREAM_KEY",
    fetch: fetchVessels,
  },
  {
    id: "tankers",
    label: "Oil tankers (live)",
    category: "Maritime",
    kind: "live",
    description: "Live AIS positions filtered to oil/chemical tankers.",
    source: "aisstream.io (AIS)",
    sourceUrl: "https://aisstream.io/",
    style: { type: "circle", color: "#ffcc00", radius: 4 },
    refreshMs: 15_000,
    requiresKey: "VITE_AISSTREAM_KEY",
    fetch: fetchTankers,
  },
  {
    id: "chokepoints",
    label: "Maritime chokepoints",
    category: "Maritime",
    kind: "reference",
    description: "Critical straits & canals for global oil and trade transit.",
    source: "Curated (EIA)",
    sourceUrl: "https://www.eia.gov/international/analysis/special-topics/World_Oil_Transit_Chokepoints",
    style: { type: "circle", color: "#ff6699", radius: 8 },
    refreshMs: 0,
    fetch: fetchChokepoints,
  },
  {
    id: "trade-routes",
    label: "Maritime trade routes",
    category: "Maritime",
    kind: "reference",
    description: "Major global shipping lanes connecting key ports & chokepoints.",
    source: "Curated",
    style: { type: "line", color: "#5fd0ff", width: 1.5 },
    refreshMs: 0,
    fetch: fetchTradeRoutes,
  },
  {
    id: "undersea-cables",
    label: "Undersea cables",
    category: "Maritime",
    kind: "reference",
    description: "Major submarine communications cable systems.",
    source: "TeleGeography / curated",
    sourceUrl: "https://www.submarinecablemap.com/",
    style: { type: "line", color: "#9d7bff", width: 1 },
    refreshMs: 0,
    fetch: fetchUnderseaCables,
  },

  // ── Aerospace ──────────────────────────────────────────────────────────────
  {
    id: "flights-commercial",
    label: "Commercial aviation",
    category: "Aerospace",
    kind: "live",
    description: "Live ADS-B positions of civilian aircraft in view.",
    source: "OpenSky Network",
    sourceUrl: "https://opensky-network.org/",
    style: { type: "circle", color: "#e0e0e0", radius: 2.5 },
    refreshMs: 20_000,
    fetch: fetchCommercialFlights,
  },
  {
    id: "flights-military",
    label: "Military aviation",
    category: "Aerospace",
    kind: "live",
    description: "Aircraft with military callsign prefixes (NATO/allied).",
    source: "OpenSky Network",
    sourceUrl: "https://opensky-network.org/",
    style: { type: "circle", color: "#ff7a00", radius: 4 },
    refreshMs: 20_000,
    fetch: fetchMilitaryFlights,
  },
  {
    id: "space-stations",
    label: "Space stations",
    category: "Aerospace",
    kind: "live",
    description: "ISS, Tiangong & crewed stations — live sub-satellite point (SGP4).",
    source: "CelesTrak TLE + SGP4",
    sourceUrl: "https://celestrak.org/",
    style: { type: "circle", color: "#ffffff", radius: 6 },
    refreshMs: 20_000,
    fetch: fetchSpaceStations,
  },
  {
    id: "sats-military",
    label: "Military / recon satellites",
    category: "Aerospace",
    kind: "live",
    description: "Catalogued military satellites — live ground positions (SGP4).",
    source: "CelesTrak (military group)",
    sourceUrl: "https://celestrak.org/",
    style: { type: "circle", color: "#ff3399", radius: 3 },
    refreshMs: 30_000,
    fetch: fetchMilitarySats,
  },
  {
    id: "sats-gnss",
    label: "Navigation satellites (GNSS)",
    category: "Aerospace",
    kind: "live",
    description: "GPS/GLONASS/Galileo/BeiDou — live ground positions (SGP4).",
    source: "CelesTrak (gnss group)",
    sourceUrl: "https://celestrak.org/",
    style: { type: "circle", color: "#66ffcc", radius: 3 },
    refreshMs: 30_000,
    fetch: fetchGnss,
  },
  {
    id: "sats-starlink",
    label: "Starlink constellation",
    category: "Aerospace",
    kind: "live",
    description: "SpaceX Starlink — live ground positions (SGP4).",
    source: "CelesTrak (starlink group)",
    sourceUrl: "https://celestrak.org/",
    style: { type: "circle", color: "#88aaff", radius: 1.5 },
    refreshMs: 30_000,
    fetch: fetchStarlink,
  },
  {
    id: "spaceports",
    label: "Spaceports",
    category: "Aerospace",
    kind: "reference",
    description: "Active and historic orbital launch sites.",
    source: "Curated",
    style: { type: "circle", color: "#ffaa00", radius: 6 },
    refreshMs: 0,
    fetch: fetchSpaceports,
  },

  // ── Energy & Infrastructure ────────────────────────────────────────────────
  {
    id: "pipelines",
    label: "Oil & gas pipelines",
    category: "Energy & Infrastructure",
    kind: "reference",
    description: "Major strategic oil and gas pipeline systems.",
    source: "Curated",
    style: { type: "line", color: "#ffa64d", width: 1.5 },
    refreshMs: 0,
    fetch: fetchPipelines,
  },
  {
    id: "storage",
    label: "Storage facilities",
    category: "Energy & Infrastructure",
    kind: "reference",
    description: "Strategic petroleum reserves and major oil storage hubs.",
    source: "Curated",
    style: { type: "circle", color: "#d9b38c", radius: 5 },
    refreshMs: 0,
    fetch: fetchStorageFacilities,
  },
  {
    id: "datacenters",
    label: "AI / hyperscale datacenters",
    category: "Energy & Infrastructure",
    kind: "reference",
    description: "Major AI training & hyperscale datacenter campuses.",
    source: "Curated",
    style: { type: "circle", color: "#00ffaa", radius: 5 },
    refreshMs: 0,
    fetch: fetchDatacenters,
  },
  {
    id: "manufacturing",
    label: "Manufacturing units",
    category: "Energy & Infrastructure",
    kind: "reference",
    description: "Strategic semiconductor, auto and industrial plants.",
    source: "Curated",
    style: { type: "circle", color: "#b3b3ff", radius: 5 },
    refreshMs: 0,
    fetch: fetchManufacturing,
  },

  // ── Cyber & Networks ───────────────────────────────────────────────────────
  {
    id: "cyber",
    label: "Cyber threats",
    category: "Cyber & Networks",
    kind: "live",
    description: "Geolocated cyberattack, ransomware & breach reporting.",
    source: "GDELT 2.0 GEO API",
    sourceUrl: "https://www.gdeltproject.org/",
    style: { type: "circle", color: "#ff00aa", radius: 5 },
    refreshMs: 12 * MIN,
    fetch: fetchCyberThreats,
  },
  {
    id: "gps-jamming",
    label: "GPS jamming / spoofing",
    category: "Cyber & Networks",
    kind: "live",
    description: "Measured GNSS interference aggregated from aircraft navigation.",
    source: "GPSJam.org",
    sourceUrl: "https://gpsjam.org/",
    style: { type: "circle", color: "#ff5555", radius: 4 },
    refreshMs: 30 * MIN,
    fetch: fetchGpsJamming,
  },
  {
    id: "outages",
    label: "Internet outages / disruption",
    category: "Cyber & Networks",
    kind: "live",
    description: "Reported internet shutdowns and connectivity disruptions.",
    source: "GDELT 2.0 GEO API",
    sourceUrl: "https://www.gdeltproject.org/",
    style: { type: "circle", color: "#ff8c66", radius: 5 },
    refreshMs: 15 * MIN,
    fetch: fetchInternetOutages,
  },

  // ── Influence & Info-War ───────────────────────────────────────────────────
  {
    id: "psyops-index",
    label: "Info-War / PsyOps index",
    category: "Influence & Info-War",
    kind: "live",
    description:
      "Composite information-warfare index per country: Oxford cyber-troop capacity + Freedom on the Net + foreign-influence-ops + live GDELT info-ops reporting (0–100).",
    source: "Oxford OII + Freedom House + GDELT (composite)",
    sourceUrl: "https://demtech.oii.ox.ac.uk/",
    style: {
      type: "graduated",
      field: "index",
      min: 0,
      max: 100,
      colorLow: "#2a4d69",
      colorHigh: "#ff2a2a",
      radiusMin: 5,
      radiusMax: 22,
    },
    refreshMs: 30 * MIN,
    fetch: fetchPsyopsIndex,
    titleField: "title",
  },

  // ── Economy & Trade ────────────────────────────────────────────────────────
  {
    id: "tariffs",
    label: "US tariffs (by country)",
    category: "Economy & Trade",
    kind: "reference",
    description: "Tariffs imposed by the United States, by partner country.",
    source: "Curated (USTR/news)",
    style: { type: "circle", color: "#ffcc66", radius: 7 },
    refreshMs: 0,
    fetch: fetchTariffs,
  },

  // ── Hazards & Health ───────────────────────────────────────────────────────
  {
    id: "earthquakes",
    label: "Earthquakes (24h)",
    category: "Hazards & Health",
    kind: "live",
    description: "Magnitude 2.5+ earthquakes in the last 24 hours.",
    source: "USGS",
    sourceUrl: "https://earthquake.usgs.gov/",
    style: { type: "circle", color: "#ff9933", radius: 4 },
    refreshMs: 5 * MIN,
    fetch: fetchEarthquakes,
  },
  {
    id: "disease",
    label: "Disease outbreaks",
    category: "Hazards & Health",
    kind: "live",
    description: "Geolocated disease-outbreak and epidemic reporting.",
    source: "GDELT 2.0 GEO API",
    sourceUrl: "https://www.gdeltproject.org/",
    style: { type: "circle", color: "#66ff66", radius: 5 },
    refreshMs: 20 * MIN,
    fetch: fetchDiseaseOutbreaks,
  },
];

export const LAYERS_BY_ID: Record<string, LayerDefinition> = Object.fromEntries(
  LAYERS.map((l) => [l.id, l])
);

export const CATEGORIES = Array.from(new Set(LAYERS.map((l) => l.category)));
